development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://aegvhnivptvxtx:593c95a38429e79788219f70420bca5f54415642ffa1f15a3ad27fe3865ae402@ec2-54-235-119-27.compute-1.amazonaws.com:5432/d83trnfaisdlnt
  channel_prefix: sample_app_production
